function [trainedClassifier, validationAccuracy] = train_cubic_svm(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: a table containing the same predictor and response
%       columns as imported into the app.
%
%  Output:
%      trainedClassifier: a struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: a function to make predictions on new
%       data.
%
%      validationAccuracy: a double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 16-Feb-2018 19:02:39


    % Extract predictors and response
    % This code processes the data into the right shape for training the
    % model.
    inputTable = trainingData;
    % Split matrices in the input table into vectors
    inputTable = [inputTable(:,setdiff(inputTable.Properties.VariableNames, {'HOG'})), array2table(table2array(inputTable(:,{'HOG'})), 'VariableNames', {'HOG_1', 'HOG_2', 'HOG_3', 'HOG_4', 'HOG_5', 'HOG_6', 'HOG_7', 'HOG_8', 'HOG_9', 'HOG_10', 'HOG_11', 'HOG_12', 'HOG_13', 'HOG_14', 'HOG_15', 'HOG_16', 'HOG_17', 'HOG_18', 'HOG_19', 'HOG_20', 'HOG_21', 'HOG_22', 'HOG_23', 'HOG_24'})];

    predictorNames = {'Mean', 'Stdev', 'HOG_1', 'HOG_2', 'HOG_3', 'HOG_4', 'HOG_5', 'HOG_6', 'HOG_7', 'HOG_8', 'HOG_9', 'HOG_10', 'HOG_11', 'HOG_12', 'HOG_13', 'HOG_14', 'HOG_15', 'HOG_16', 'HOG_17', 'HOG_18', 'HOG_19', 'HOG_20', 'HOG_21', 'HOG_22', 'HOG_23', 'HOG_24'};
    predictors = inputTable(:, predictorNames);
    response = inputTable.OrientationFlags;
    isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

    % Train a classifier
    % This code specifies all the classifier options and trains the classifier.
    template = templateSVM(...
        'KernelFunction', 'polynomial', ...
        'PolynomialOrder', 3, ...
        'KernelScale', 'auto', ...
        'BoxConstraint', 1, ...
        'Standardize', true);
    classificationSVM = fitcecoc(...
        predictors, ...
        response, ...
        'Learners', template, ...
        'Coding', 'onevsone', ...
        'ClassNames', ['*' '*'; '*' '0'; '*' '1'; '0' '0'; '0' '1'; '1' '0'; '1' '1']);

    compactClassifier = compact(classificationSVM);
    
    % Add additional fields to the result struct
    trainedClassifier.RequiredVariables = {'Mean', 'Stdev', 'HOG'};
    trainedClassifier.UncompactedClassifier = classificationSVM;
    trainedClassifier.ClassificationSVM = compactClassifier;
    trainedClassifier.predictFcn = create_predictFcn(compactClassifier);
    trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2017b.';
    trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

    % Extract predictors and response
    % This code processes the data into the right shape for training the
    % model.
    inputTable = trainingData;
    % Split matrices in the input table into vectors
    inputTable = [inputTable(:,setdiff(inputTable.Properties.VariableNames, {'HOG'})), array2table(table2array(inputTable(:,{'HOG'})), 'VariableNames', {'HOG_1', 'HOG_2', 'HOG_3', 'HOG_4', 'HOG_5', 'HOG_6', 'HOG_7', 'HOG_8', 'HOG_9', 'HOG_10', 'HOG_11', 'HOG_12', 'HOG_13', 'HOG_14', 'HOG_15', 'HOG_16', 'HOG_17', 'HOG_18', 'HOG_19', 'HOG_20', 'HOG_21', 'HOG_22', 'HOG_23', 'HOG_24'})];

    predictorNames = {'Mean', 'Stdev', 'HOG_1', 'HOG_2', 'HOG_3', 'HOG_4', 'HOG_5', 'HOG_6', 'HOG_7', 'HOG_8', 'HOG_9', 'HOG_10', 'HOG_11', 'HOG_12', 'HOG_13', 'HOG_14', 'HOG_15', 'HOG_16', 'HOG_17', 'HOG_18', 'HOG_19', 'HOG_20', 'HOG_21', 'HOG_22', 'HOG_23', 'HOG_24'};
    predictors = inputTable(:, predictorNames);
    response = inputTable.OrientationFlags;
    isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

    % Perform cross-validation
    partitionedModel = crossval(trainedClassifier.UncompactedClassifier, 'KFold', 5);

    % Compute validation predictions
    [validationPredictions, validationScores] = kfoldPredict(partitionedModel);

    % Compute validation accuracy
    validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
end


function fn = create_predictFcn(classificationSVM)
    predictorNames = {'Mean', 'Stdev', 'HOG_1', 'HOG_2', 'HOG_3', 'HOG_4', 'HOG_5', 'HOG_6', 'HOG_7', 'HOG_8', 'HOG_9', 'HOG_10', 'HOG_11', 'HOG_12', 'HOG_13', 'HOG_14', 'HOG_15', 'HOG_16', 'HOG_17', 'HOG_18', 'HOG_19', 'HOG_20', 'HOG_21', 'HOG_22', 'HOG_23', 'HOG_24'};
    
    % Create the result struct with predict function
    splitMatricesInTableFcn = @(t) [t(:,setdiff(t.Properties.VariableNames, {'HOG'})), array2table(table2array(t(:,{'HOG'})), 'VariableNames', {'HOG_1', 'HOG_2', 'HOG_3', 'HOG_4', 'HOG_5', 'HOG_6', 'HOG_7', 'HOG_8', 'HOG_9', 'HOG_10', 'HOG_11', 'HOG_12', 'HOG_13', 'HOG_14', 'HOG_15', 'HOG_16', 'HOG_17', 'HOG_18', 'HOG_19', 'HOG_20', 'HOG_21', 'HOG_22', 'HOG_23', 'HOG_24'})];
    extractPredictorsFromTableFcn = @(t) t(:, predictorNames);
    predictorExtractionFcn = @(x) extractPredictorsFromTableFcn(splitMatricesInTableFcn(x));
    svmPredictFcn = @(x) predict(classificationSVM, x);
    fn = @(x) svmPredictFcn(predictorExtractionFcn(x));
end