function [out, t] = count_predited_flags(flags)
    
    o = categorical(cellstr(flags), {'**', '*0', '*1', '00', '01', '10', '11'}, 'Protected', true);
    c = countcats(o);
    
    votes = [...
                1.5 * c(4) + 0.5 * c(2), ...
                1.5 * c(5) + 0.5 * c(3), ...
                1.5 * c(6) + 0.5 * c(2), ...
                1.5 * c(7) + 0.5 * c(3), ...
            ];
    
    [t, out] = max(votes);
end
